CREATE DATABASE GIMNASIOBD;
USE GIMNASIOBD;
/*DROP DATABASE GIMNASIOBD;*/

/*CREACION TABLA ROL*/
CREATE TABLE ROL(
	idRol INT(12) NOT NULL,
	nombreRol VARCHAR(20) NOT NULL
);

/*CREACION TABLA TIPO IDENTIFICACION*/
CREATE TABLE TIPO_IDENTIFICACION(
	idTipoDocumento INT(12) NOT NULL,
	nombreDocumento VARCHAR(25) NOT NULL
);

/*CREACION TABLA USUARIOS*/
CREATE TABLE USUARIOS(
	idUsuario INT(12) NOT NULL,
	NumeroIdentificacion VARCHAR(12) NOT NULL ,
	passwordUsuario VARCHAR(20) NOT NULL,
	estadoUsuario INT NOT NULL,
	idRolFK INT(12) NOT NULL,
	idTipoDocumentoFK INT(12) NOT NULL
);

/*CREACION TABLA INSTRUCTORES*/
CREATE TABLE INSTRUCTORES(
	idInstructor INT(12) NOT NULL ,
    nombreInstructor VARCHAR(35) NOT NULL,
    apellidoInstructor VARCHAR(35) NOT NULL,
    correoInstructor VARCHAR(100) NOT NULL,
    telefonoInstructor VARCHAR(11) NOT NULL,
    estadoInstructor INT NOT NULL, 
    idUsuarioFK INT(12) NOT NULL 
);

/*CREACION TABLA CLIENTES*/
CREATE TABLE CLIENTES(
	idCliente INT(12) NOT NULL ,
    nombreCliente VARCHAR(35) NOT NULL,
    apellidoCliente VARCHAR(35) NOT NULL,
    fechaNacimientoCliente DATE NOT NULL,
    correoCliente VARCHAR(100) NOT NULL,
    telefonoCliente VARCHAR(11) NOT NULL,
    estadoCliente INT NOT NULL, 
    idUsuarioFK INT(12) NOT NULL
);

/*CREACION TABLA PROGRAMACION*/
CREATE TABLE PROGRAMACION(
	idProgramacion INT(12) NOT NULL ,
	fechaInicioPro DATE NOT NULL,
    fechaFinPro DATE NOT NULL,
    idUsuarioFK INT(12) NOT NULL
);

/*CREACION TABLA ASISTENCIA*/
CREATE TABLE ASISTENCIAS(
	idAsistencia INT(12) NOT NULL,
    fechaHoraIngreso DATETIME NOT NULL,
    fechaHoraSalida DATETIME NOT NULL,
    idProgramacionFK INT(12) NOT NULL
);

/*CREACION TABLA METODOLOGIA*/
CREATE TABLE METODOLOGIA(
	idMetodologia INT(12) NOT NULL,
    nombreMetodologia VARCHAR(50) NOT NULL
);

/*CREACION TABLA SUSCRIPCION_METODOLOGIA*/
CREATE TABLE SUSCRIPCION_METODOLOGIA(
	idSuscripcionFK INT(12) NOT NULL,
    idMetodologiaFK INT(12) NOT NULL,
    fechaMetodologiaInicio DATE NOT NULL,
    fechaMetodologiaFin DATE NOT NULL
);

/*CREACION TABLA SUSCRIPCIONES*/
CREATE TABLE SUSCRIPCIONES(
	idSuscripcion INT(12) NOT NULL,
    valorSuscripcion FLOAT NOT NULL,
    fechaSuscripcion DATE NOT NULL,
    estadoSuscripcion INT NOT NULL,
    descripcionNovedad VARCHAR(500),
    idClienteFK INT(12) NOT NULL
);

/*CREACION TABLA PAGOS*/
CREATE TABLE PAGOS(
	idPago INT(12) NOT NULL,
    fechaPago DATE NOT NULL,
    valorPago FLOAT NOT NULL,
    descripcionPago VARCHAR(200) NOT NULL,
    urlSoportePago VARCHAR(500) NOT NULL,
    idSuscripcionFK INT(12) NOT NULL
);

/*CREACION TABLA FICHA ANTROPOMETRICA*/
CREATE TABLE FICHA_ANTROPOMETRICA(
	idFicha INT(12) NOT NULL,
    fechaFicha DATE NOT NULL,
    EstaturaCliente FLOAT NOT NULL,
    pesoCliente FLOAT NOT NULL,
    descripcionFicha VARCHAR(200) NOT NULL,
    idSuscripcionFK INT(12) NOT NULL
);

/*CREACION TABLA PARTES DEL CUERPO*/
CREATE TABLE PARTE_DEL_CUERPO(
	idParteDelCuerpo INT(12) NOT NULL,
    nombreParteCuerpo VARCHAR(35) NOT NULL
);


/*CREACION TABLA PARTE_CUERPO_EJERCICIO*/
CREATE TABLE PARTE_CUERPO_EJERCICIO(
	idFichaFK INT(12) NOT NULL,
    idParteDelCuerpoFK INT(12) NOT NULL,
    medida FLOAT NOT NULL
);

/*CREACION TABLA EJERCICIOS*/
CREATE TABLE EJERCICIOS(
	idEjercicio INT(12) NOT NULL,
    idParteDelCuerpoFK INT(12) NOT NULL,
    nombreEjercicio VARCHAR(50) NOT NULL,
    urlImagen VARCHAR(500) NOT NULL
);

/*CREACION TABLA SERIES DE EJERCICIO*/
CREATE TABLE SERIE_DE_EJERCICIO(
	idSerie INT(12) NOT NULL,
    nombreSerieEjercicio VARCHAR(50) NOT NULL,
    descripcionSerieEjercicio VARCHAR(300) NOT NULL,
	repeticionEjercicio INT NOT NULL,
    secuenciaEjercicio INT NOT NULL,
    idMetodologiaFK INT NOT NULL
);

/*CREACION TABLA DE SERIES_EJERCICIOS*/
CREATE TABLE TB_SERIES_EJERCICIOS(
	idEjercicioFK INT(12) NOT NULL,
    idSerieFK INT(12) NOT NULL
);

/*--------------------------------INDICES----------------------------*/

/*INDICES DE TABLA USUARIOS*/
ALTER TABLE USUARIOS
ADD PRIMARY KEY (idUsuario),
ADD  KEY  FK_idTipoDocumentoFK_USUARIOS_idx (idTipoDocumentoFK),
ADD  KEY  FK_idRolFK_USUARIOS_idx (idRolFK);

/*INDICES DE TABLA ROL*/
ALTER TABLE ROL
ADD PRIMARY KEY (idRol);

/*INDICES DE TABLA TIPO IDENTIFICACION*/
ALTER TABLE TIPO_IDENTIFICACION
ADD PRIMARY KEY (idTipoDocumento);

/*INDICES DE TABLA INSTRUCTORES*/
ALTER TABLE INSTRUCTORES
ADD PRIMARY KEY (idInstructor),
ADD  KEY  FK_idUsuarioFK_INSTRUCTORES_idx (idUsuarioFK);

/*INDICES DE TABLA CLIENTES*/
ALTER TABLE CLIENTES
ADD PRIMARY KEY (idCliente),
ADD  KEY  FK_idUsuarioFK_CLIENTES_idx (idUsuarioFK);

/*INDICES DE TABLA PROGRAMACION*/
ALTER TABLE PROGRAMACION
ADD PRIMARY KEY (idProgramacion),
ADD  KEY  FK_idUsuarioFK_PROGRAMACION_idx (idUsuarioFK);

/*INDICES DE TABLA ASISTENCIAS*/
ALTER TABLE ASISTENCIAS
ADD PRIMARY KEY (idAsistencia),
ADD  KEY  FK_idProgramacionFK_ASISTENCIAS_idx (idProgramacionFK);

/*INDICES DE TABLA METODOLOGIA*/
ALTER TABLE METODOLOGIA
ADD PRIMARY KEY (idMetodologia);

/*INDICES SUSCRIPCION_METODOLOGIA*/
ALTER TABLE SUSCRIPCION_METODOLOGIA
ADD PRIMARY KEY (idMetodologiaFK,idSuscripcionFK),
ADD  KEY  FK_idMetodologiaFK_SUSCRIPCION_METODOLOGIA_idx (idMetodologiaFK),
ADD  KEY  FK_idSuscripcionFK_SUSCRIPCION_METODOLOGIA_idx (idSuscripcionFK);

/*INDICES DE TABLA SUSCRIPCIONES*/
ALTER TABLE SUSCRIPCIONES
ADD PRIMARY KEY (idSuscripcion),
ADD  KEY  FK_idClienteFK_SUSCRIPCIONES_idx (idClienteFK);

/*INDICES DE TABLA PAGOS*/
ALTER TABLE PAGOS
ADD PRIMARY KEY (idPago),
ADD  KEY  FK_idSuscripcionFK_PAGOS_idx (idSuscripcionFK);

/*INDICES DE TABLA FICHA_ANTROPOMETRICA*/
ALTER TABLE FICHA_ANTROPOMETRICA
ADD PRIMARY KEY (idFicha),
ADD  KEY  FK_idSuscripcionFK_FICHA_ANTROPOMETRICA_idx (idSuscripcionFK);

/*INDICES DE TABLA PARTES DEL CUERPO*/
ALTER TABLE PARTE_DEL_CUERPO
ADD PRIMARY KEY (idParteDelCuerpo);

/*INDICES DE PARTE_CUERPO_EJERCICIO*/
ALTER TABLE PARTE_CUERPO_EJERCICIO
ADD PRIMARY KEY (idFichaFK,idParteDelCuerpoFK),
ADD  KEY  FK_idFichaFK_PARTE_CUERPO_EJERCICIO_idx (idFichaFK),
ADD  KEY  FK_idParteDelCuerpoFK_PARTE_CUERPO_EJERCICIO_idx (idParteDelCuerpoFK);

/*INDICES DE TABLA EJERCICIOS*/
ALTER TABLE EJERCICIOS
ADD PRIMARY KEY (idEjercicio);

/*INDICES DE TABLA SERIE_DE_EJERCICIO*/
ALTER TABLE SERIE_DE_EJERCICIO
ADD PRIMARY KEY (idSerie),
ADD  KEY  FK_idMetodologiaFK_SERIE_DE_EJERCICIO_idx (idMetodologiaFK);

/*INDICES DE TABLA TB_SERIES_EJERCICIOS*/
ALTER TABLE TB_SERIES_EJERCICIOS
ADD PRIMARY KEY (idSerieFK,idEjercicioFK),
ADD  KEY  FK_idSerieFK_TB_SERIES_EJERCICIOS_idx (idSerieFK),
ADD  KEY  FK_idEjercicioFK_TB_SERIES_EJERCICIOS_idx (idEjercicioFK);

/*-------------------------------------------FILTROS----------------------------*/

/*FILTROS PARA LA TABLA USUARIOS*/
ALTER TABLE USUARIOS
ADD CONSTRAINT FK_idTipoDocumentoFK_USUARIOS FOREIGN KEY (idTipoDocumentoFK)
REFERENCES TIPO_IDENTIFICACION (idTipoDocumento) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idRolFK_USUARIOS FOREIGN KEY (idRolFK)
REFERENCES ROL (idRol) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA INSTRUCTORES*/
ALTER TABLE INSTRUCTORES
ADD CONSTRAINT FK_idUsuarioFK_INSTRUCTORES FOREIGN KEY (idUsuarioFK)
REFERENCES USUARIOS (idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA PROGRAMACION*/
ALTER TABLE PROGRAMACION
ADD CONSTRAINT FK_idUsuarioFK_PROGRAMACION FOREIGN KEY (idUsuarioFK)
REFERENCES USUARIOS (idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA CLIENTES*/
ALTER TABLE CLIENTES
ADD CONSTRAINT FK_idUsuarioFK_CLIENTES FOREIGN KEY (idUsuarioFK)
REFERENCES USUARIOS (idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA ASISTENCIAS*/
ALTER TABLE ASISTENCIAS
ADD CONSTRAINT FK_idProgramacionFK_ASISTENCIAS FOREIGN KEY (idProgramacionFK)
REFERENCES PROGRAMACION (idProgramacion) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA SUSCRIPCIONES*/
ALTER TABLE SUSCRIPCIONES
ADD CONSTRAINT FK_idClienteFK_SUSCRIPCIONES FOREIGN KEY (idClienteFK)
REFERENCES CLIENTES (idCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA SUSCRIPCION_METODOLOGIA*/
ALTER TABLE SUSCRIPCION_METODOLOGIA
ADD CONSTRAINT FK_idMetodologiaFK_SUSCRIPCION_METODOLOGIA FOREIGN KEY(idMetodologiaFK)
REFERENCES METODOLOGIA (idMetodologia) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idSuscripcionFK_SUSCRIPCION_METODOLOGIA FOREIGN KEY(idSuscripcionFK)
REFERENCES SUSCRIPCIONES (idSuscripcion) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA PAGOS*/
ALTER TABLE PAGOS
ADD CONSTRAINT FK_idSuscripcionFK_PAGOS FOREIGN KEY (idSuscripcionFK)
REFERENCES SUSCRIPCIONES (idSuscripcion) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA FICHA_ANTROPOMETRICA*/
ALTER TABLE FICHA_ANTROPOMETRICA
ADD CONSTRAINT FK_idSuscripcionFK_FICHA_ANTROPOMETRICA FOREIGN KEY (idSuscripcionFK)
REFERENCES SUSCRIPCIONES (idSuscripcion) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA PARTE_CUERPO_EJERCICIO*/
ALTER TABLE PARTE_CUERPO_EJERCICIO
ADD CONSTRAINT FK_idFichaFK_PARTE_CUERPO_EJERCICIO FOREIGN KEY (idFichaFK)
REFERENCES FICHA_ANTROPOMETRICA (idFicha) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idParteDelCuerpoFK_PARTE_CUERPO_EJERCICIO FOREIGN KEY (idParteDelCuerpoFK)
REFERENCES PARTE_DEL_CUERPO (idParteDelCuerpo) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA TB_SERIES_EJERCICIOS*/
ALTER TABLE TB_SERIES_EJERCICIOS
ADD CONSTRAINT FK_idSerieFK_TB_SERIES_EJERCICIOS FOREIGN KEY (idSerieFK)
REFERENCES SERIE_DE_EJERCICIO (idSerie) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idEjercicioFK_TB_SERIES_EJERCICIOS FOREIGN KEY (idEjercicioFK)
REFERENCES EJERCICIOS (idEjercicio) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA TABLA SERIE DE EJERCICIO*/
ALTER TABLE SERIE_DE_EJERCICIO
ADD CONSTRAINT FK_idMetodologiaFK_SERIE_DE_EJERCICIO FOREIGN KEY (idMetodologiaFK)
REFERENCES METODOLOGIA (idMetodologia) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*-----------------------------VALORES UNICOS----------------------------------------------*/

/*VALORES UNICOS PARA LA TABLA INSTRUCTORES*/
CREATE UNIQUE INDEX IND_correoInstructor ON INSTRUCTORES (correoInstructor);
CREATE UNIQUE INDEX IND_telefonoInstructor ON INSTRUCTORES (telefonoInstructor);
CREATE UNIQUE INDEX IND_idInstructor ON INSTRUCTORES (idInstructor);
CREATE UNIQUE INDEX IND_idUsuarioFK ON INSTRUCTORES (idUsuarioFK);

/*VALORES UNICOS PARA LA TABLA CLIENTES*/
CREATE UNIQUE INDEX IND_correoCliente ON CLIENTES (correoCliente);
CREATE UNIQUE INDEX IND_telefonoCliente ON CLIENTES (telefonoCliente);
CREATE UNIQUE INDEX IND_idCliente ON CLIENTES (idCliente);
CREATE UNIQUE INDEX IND_idUsuarioFK ON CLIENTES (idUsuarioFK);

/*VALORES UNICOS PARA LA TABLA USUARIOS*/
CREATE UNIQUE INDEX IND_NumeroIdentificacion ON USUARIOS (NumeroIdentificacion);

