CREATE DATABASE GIMNASIOBD;
USE GIMNASIOBD;
/*DROP DATABASE GIMNASIOBD;*/

/*CREACION TABLA ROL*/
CREATE TABLE ROL(
	idRol INT(12) NOT NULL,
	nombreRol VARCHAR(20) NOT NULL
);

/*CREACION TABLA TIPO IDENTIFICACION*/
CREATE TABLE TIPO_IDENTIFICACION(
	idTipoDocumento INT(12) NOT NULL,
	nombreDocumento VARCHAR(25) NOT NULL
);

/*CREACION TABLA USUARIOS*/
CREATE TABLE USUARIOS(
	idUsuario INT(12) NOT NULL,
	NumeroIdentificacion VARCHAR(12) NOT NULL ,
	passwordUsuario VARCHAR(20) NOT NULL,
	estadoUsuario INT NOT NULL,
	idRolFK INT(12) NOT NULL,
	idTipoDocumentoFK INT(12) NOT NULL
);

/*CREACION TABLA INSTRUCTORES*/
CREATE TABLE INSTRUCTORES(
	idInstructor INT(12) NOT NULL ,
    nombreInstructor VARCHAR(35) NOT NULL,
    apellidoInstructor VARCHAR(35) NOT NULL,
    correoInstructor VARCHAR(100) NOT NULL,
    telefonoInstructor VARCHAR(11) NOT NULL,
    estadoInstructor INT NOT NULL, 
    idUsuarioFK INT(12) NOT NULL 
);

/*CREACION TABLA CLIENTES*/
CREATE TABLE CLIENTES(
	idCliente INT(12) NOT NULL ,
    nombreCliente VARCHAR(35) NOT NULL,
    apellidoCliente VARCHAR(35) NOT NULL,
    fechaNacimientoCliente DATE NOT NULL,
    correoCliente VARCHAR(100) NOT NULL,
    telefonoCliente VARCHAR(11) NOT NULL,
    estadoCliente INT NOT NULL, 
    idUsuarioFK INT(12) NOT NULL
);

/*CREACION TABLA PROGRAMACION*/
CREATE TABLE PROGRAMACION(
	idProgramacion INT(12) NOT NULL ,
	fechaInicioPro DATE NOT NULL,
    fechaFinPro DATE NOT NULL,
    idUsuarioFK INT(12) NOT NULL
);

/*CREACION TABLA ASISTENCIA*/
CREATE TABLE ASISTENCIAS(
	idAsistencia INT(12) NOT NULL,
    fechaHoraIngreso DATETIME NOT NULL,
    fechaHoraSalida DATETIME NOT NULL,
    idProgramacionFK INT(12) NOT NULL
);

/*CREACION TABLA METODOLOGIA*/
CREATE TABLE METODOLOGIA(
	idMetodologia INT(12) NOT NULL,
    nombreMetodologia VARCHAR(50) NOT NULL
);

/*CREACION TABLA SUSCRIPCIONES*/
CREATE TABLE SUSCRIPCIONES(
	idSuscripcion INT(12) NOT NULL,
    valorSuscripcion FLOAT NOT NULL,
    fechaSuscripcion DATE NOT NULL,
    estadoSuscripcion INT NOT NULL,
    idClienteFK INT(12) NOT NULL,
    idMetodologiaFK INT(12) NOT NULL
);

/*CREACION TABLA PAGOS*/
CREATE TABLE PAGOS(
	idPago INT(12) NOT NULL,
    fechaPago DATE NOT NULL,
    valorPago FLOAT NOT NULL,
    descripcionPago VARCHAR(200) NOT NULL,
    urlSoportePago VARCHAR(500) NOT NULL,
    idSuscripcionFK INT(12) NOT NULL
);

/*CREACION TABLA TIPO NOVEDAD*/
CREATE TABLE TIPO_NOVEDAD(
	idTipoNov INT(12) NOT NULL,
    nombreNovedad VARCHAR(35) NOT NULL
);

/*CREACION TABLA NOVEDAD*/
CREATE TABLE NOVEDAD(
	idNovedad INT(12) NOT NULL,
    fechaNovedad DATE NOT NULL,
    descripcionNovedad VARCHAR(200) NOT NULL,
    idSuscripcionFK INT(12) NOT NULL,
    idTipoNovFK INT(12) NOT NULL
);


/*CREACION TABLA FICHA ANTROPOMETRICA*/
CREATE TABLE FICHA_ANTROPOMETRICA(
	idFicha INT(12) NOT NULL,
    fechaFicha DATE NOT NULL,
    EstaturaCliente FLOAT NOT NULL,
    pesoCliente FLOAT NOT NULL,
    descripcionFicha VARCHAR(200) NOT NULL,
    idSuscripcionFK INT(12) NOT NULL
);

/*CREACION TABLA PARTES DEL CUERPO*/
CREATE TABLE PARTE_DEL_CUERPO(
	idParteDelCuerpo INT(12) NOT NULL,
    nombreParteCuerpo VARCHAR(35) NOT NULL
);


/*CREACION TABLA FICHA MEDIDAS*/
CREATE TABLE FICHA_MEDIDA(
	idFichaFK INT(12) NOT NULL,
    idParteDelCuerpoFK INT(12) NOT NULL,
    medida FLOAT NOT NULL
);

/*CREACION TABLA EJERCICIOS*/
CREATE TABLE EJERCICIOS(
	idEjercicio INT(12) NOT NULL,
    idParteDelCuerpoFK INT(12) NOT NULL,
    nombreEjercicio VARCHAR(50) NOT NULL
);

/*CREACION TABLA SUSCRIPCIONES EJERCICIOS*/
CREATE TABLE SUSCRIPCIONES_SERIE_EJERCICIO(
	idSerieFK INT(12) NOT NULL,
    idSuscripcionFK INT(12) NOT NULL,
    fechaInicio DATE NOT NULL,
    fechaFin DATE NOT NULL
);

/*CREACION TABLA IMAGENES*/
CREATE TABLE IMAGENES(
	idImagen INT(12) NOT NULL,
    urlImagen VARCHAR(500) NOT NULL,
    descripcionImagen VARCHAR(300) NOT NULL,
    idEjercicioFK INT(12) NOT NULL
);

/*CREACION TABLA SERIES DE EJERCICIO*/
CREATE TABLE SERIE_DE_EJERCICIO(
	idSerie INT(12) NOT NULL,
    nombreSerieEjercicio VARCHAR(50) NOT NULL,
    descripcionSerieEjercicio VARCHAR(300) NOT NULL,
	repeticionEjercicio INT NOT NULL,
    secuenciaEjercicio INT NOT NULL
);

/*CREACION TABLA DE RUTINAS DE EJERCICIO*/
CREATE TABLE RUTINAS_EJERCICIO(
	idEjercicioFK INT(12) NOT NULL,
    idSerieFK INT(12) NOT NULL
);

/*--------------------------------INDICES----------------------------*/

/*INDICES DE TABLA USUARIOS*/
ALTER TABLE USUARIOS
ADD PRIMARY KEY (idUsuario),
ADD  KEY  FK_idTipoDocumentoFK_USUARIOS_idx (idTipoDocumentoFK),
ADD  KEY  FK_idRolFK_USUARIOS_idx (idRolFK);

/*INDICES DE TABLA ROL*/
ALTER TABLE ROL
ADD PRIMARY KEY (idRol);

/*INDICES DE TABLA TIPO IDENTIFICACION*/
ALTER TABLE TIPO_IDENTIFICACION
ADD PRIMARY KEY (idTipoDocumento);

/*INDICES DE TABLA INSTRUCTORES*/
ALTER TABLE INSTRUCTORES
ADD PRIMARY KEY (idInstructor),
ADD  KEY  FK_idUsuarioFK_INSTRUCTORES_idx (idUsuarioFK);

/*INDICES DE TABLA CLIENTES*/
ALTER TABLE CLIENTES
ADD PRIMARY KEY (idCliente),
ADD  KEY  FK_idUsuarioFK_CLIENTES_idx (idUsuarioFK);

/*INDICES DE TABLA PROGRAMACION*/
ALTER TABLE PROGRAMACION
ADD PRIMARY KEY (idProgramacion),
ADD  KEY  FK_idUsuarioFK_PROGRAMACION_idx (idUsuarioFK);

/*INDICES DE TABLA ASISTENCIAS*/
ALTER TABLE ASISTENCIAS
ADD PRIMARY KEY (idAsistencia),
ADD  KEY  FK_idProgramacionFK_ASISTENCIAS_idx (idProgramacionFK);

/*INDICES DE TABLA METODOLOGIA*/
ALTER TABLE METODOLOGIA
ADD PRIMARY KEY (idMetodologia);

/*INDICES DE TABLA SUSCRIPCIONES*/
ALTER TABLE SUSCRIPCIONES
ADD PRIMARY KEY (idSuscripcion),
ADD  KEY  FK_idMetodologiaFK_SUSCRIPCIONES_idx (idMetodologiaFK),
ADD  KEY  FK_idClienteFK_SUSCRIPCIONES_idx (idClienteFK);

/*INDICES DE TABLA PAGOS*/
ALTER TABLE PAGOS
ADD PRIMARY KEY (idPago),
ADD  KEY  FK_idSuscripcionFK_PAGOS_idx (idSuscripcionFK);

/*INDICES DE TABLA TIPO DE NOVEDAD*/
ALTER TABLE TIPO_NOVEDAD
ADD PRIMARY KEY (idTipoNov);

/*INDICES DE TABLA NOVEDAD*/
ALTER TABLE NOVEDAD
ADD PRIMARY KEY (idNovedad),
ADD  KEY  FK_idSuscripcionFK_NOVEDAD_idx (idSuscripcionFK),
ADD  KEY  FK_idTipoNovFK_NOVEDAD_idx (idTipoNovFK);

/*INDICES DE TABLA FICHA_ANTROPOMETRICA*/
ALTER TABLE FICHA_ANTROPOMETRICA
ADD PRIMARY KEY (idFicha),
ADD  KEY  FK_idSuscripcionFK_FICHA_ANTROPOMETRICA_idx (idSuscripcionFK);

/*INDICES DE TABLA PARTES DEL CUERPO*/
ALTER TABLE PARTE_DEL_CUERPO
ADD PRIMARY KEY (idParteDelCuerpo);

/*INDICES DE TABLA FICHA_MEDIDA*/
ALTER TABLE FICHA_MEDIDA
ADD PRIMARY KEY (idFichaFK,idParteDelCuerpoFK),
ADD  KEY  FK_idFichaFK_FICHA_MEDIDA_idx (idFichaFK),
ADD  KEY  FK_idParteDelCuerpoFK_FICHA_MEDIDA_idx (idParteDelCuerpoFK);

/*INDICES DE TABLA EJERCICIOS*/
ALTER TABLE EJERCICIOS
ADD PRIMARY KEY (idEjercicio),
ADD KEY FK_idParteDelCuerpoFK_EJERCICIOS_idx (idParteDelCuerpoFK);

/*INDICES DE TABLA SUSCRIPCIONES_EJERCICIO*/
ALTER TABLE SUSCRIPCIONES_SERIE_EJERCICIO
ADD PRIMARY KEY (idSuscripcionFK,idSerieFK),
ADD  KEY  FK_idSuscripcionFK_SUSCRIPCIONES_EJERCICIO_idx (idSuscripcionFK),
ADD  KEY  FK_idSerieFK_SUSCRIPCIONES_EJERCICIO_idx (idSerieFK);

/*INDICES DE TABLA IMAGENES*/
ALTER TABLE IMAGENES
ADD PRIMARY KEY (idImagen),
ADD  KEY  FK_idEjercicioFK_IMAGENES_idx (idEjercicioFK);

/*INDICES DE TABLA SERIE_DE_EJERCICIO*/
ALTER TABLE SERIE_DE_EJERCICIO
ADD PRIMARY KEY (idSerie);

/*INDICES DE TABLA RUTINAS_EJERCICIO*/
ALTER TABLE RUTINAS_EJERCICIO
ADD PRIMARY KEY (idSerieFK,idEjercicioFK),
ADD  KEY  FK_idSerieFK_RUTINAS_EJERCICIO_idx (idSerieFK),
ADD  KEY  FK_idEjercicioFK_RUTINAS_EJERCICIO_idx (idEjercicioFK);

/*-------------------------------------------FILTROS----------------------------*/

/*FILTROS PARA LA TABLA USUARIOS*/
ALTER TABLE USUARIOS
ADD CONSTRAINT FK_idTipoDocumentoFK_USUARIOS FOREIGN KEY (idTipoDocumentoFK)
REFERENCES TIPO_IDENTIFICACION (idTipoDocumento) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idRolFK_USUARIOS FOREIGN KEY (idRolFK)
REFERENCES ROL (idRol) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA INSTRUCTORES*/
ALTER TABLE INSTRUCTORES
ADD CONSTRAINT FK_idUsuarioFK_INSTRUCTORES FOREIGN KEY (idUsuarioFK)
REFERENCES USUARIOS (idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA PROGRAMACION*/
ALTER TABLE PROGRAMACION
ADD CONSTRAINT FK_idUsuarioFK_PROGRAMACION FOREIGN KEY (idUsuarioFK)
REFERENCES USUARIOS (idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA CLIENTES*/
ALTER TABLE CLIENTES
ADD CONSTRAINT FK_idUsuarioFK_CLIENTES FOREIGN KEY (idUsuarioFK)
REFERENCES USUARIOS (idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA ASISTENCIAS*/
ALTER TABLE ASISTENCIAS
ADD CONSTRAINT FK_idProgramacionFK_ASISTENCIAS FOREIGN KEY (idProgramacionFK)
REFERENCES PROGRAMACION (idProgramacion) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA SUSCRIPCIONES*/
ALTER TABLE SUSCRIPCIONES
ADD CONSTRAINT FK_idMetodologiaFK_SUSCRIPCIONES FOREIGN KEY (idMetodologiaFK)
REFERENCES METODOLOGIA (idMetodologia) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idClienteFK_SUSCRIPCIONES FOREIGN KEY (idClienteFK)
REFERENCES CLIENTES (idCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA PAGOS*/
ALTER TABLE PAGOS
ADD CONSTRAINT FK_idSuscripcionFK_PAGOS FOREIGN KEY (idSuscripcionFK)
REFERENCES SUSCRIPCIONES (idSuscripcion) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA NOVEDAD*/
ALTER TABLE NOVEDAD
ADD CONSTRAINT FK_idSuscripcionFK_NOVEDAD FOREIGN KEY (idSuscripcionFK)
REFERENCES SUSCRIPCIONES (idSuscripcion) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idTipoNovFK_NOVEDAD FOREIGN KEY (idTipoNovFK)
REFERENCES TIPO_NOVEDAD (idTipoNov) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA FICHA_ANTROPOMETRICA*/
ALTER TABLE FICHA_ANTROPOMETRICA
ADD CONSTRAINT FK_idSuscripcionFK_FICHA_ANTROPOMETRICA FOREIGN KEY (idSuscripcionFK)
REFERENCES SUSCRIPCIONES (idSuscripcion) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA FICHA_MEDIDA*/
ALTER TABLE FICHA_MEDIDA
ADD CONSTRAINT FK_idFichaFK_FICHA_MEDIDA FOREIGN KEY (idFichaFK)
REFERENCES FICHA_ANTROPOMETRICA (idFicha) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idParteDelCuerpoFK_FICHA_MEDIDA FOREIGN KEY (idParteDelCuerpoFK)
REFERENCES PARTE_DEL_CUERPO (idParteDelCuerpo) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA SUSCRIPCIONES_EJERCICIO*/
ALTER TABLE SUSCRIPCIONES_SERIE_EJERCICIO
ADD CONSTRAINT FK_idSuscripcionFK_SUSCRIPCIONES_SERIE_EJERCICIO FOREIGN KEY (idSuscripcionFK)
REFERENCES SUSCRIPCIONES (idSuscripcion) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idSerieFK_SUSCRIPCIONES_SERIE_EJERCICIO FOREIGN KEY (idSerieFK)
REFERENCES SERIE_DE_EJERCICIO (idSerie) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA IMAGENES*/
ALTER TABLE IMAGENES
ADD CONSTRAINT FK_idEjercicioFK_IMAGENES FOREIGN KEY (idEjercicioFK)
REFERENCES EJERCICIOS (idEjercicio) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA LA TABLA RUTINAS_EJERCICIO*/
ALTER TABLE RUTINAS_EJERCICIO
ADD CONSTRAINT FK_idSerieFK_RUTINAS_EJERCICIO FOREIGN KEY (idSerieFK)
REFERENCES SERIE_DE_EJERCICIO (idSerie) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_idEjercicioFK_RUTINAS_EJERCICIO FOREIGN KEY (idEjercicioFK)
REFERENCES EJERCICIOS (idEjercicio) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*FILTROS PARA TABLA EJERCICIOS*/
ALTER TABLE EJERCICIOS
ADD CONSTRAINT FK_idParteDelCuerpoFK_EJERCICIOS FOREIGN KEY (idParteDelCuerpoFK)
REFERENCES PARTE_DEL_CUERPO (idParteDelCuerpo) ON DELETE NO ACTION ON UPDATE NO ACTION; 

/*-----------------------------VALORES UNICOS----------------------------------------------*/

/*VALORES UNICOS PARA LA TABLA INSTRUCTORES*/
CREATE UNIQUE INDEX INDICE1 ON INSTRUCTORES (correoInstructor);
CREATE UNIQUE INDEX INDICE2 ON INSTRUCTORES (telefonoInstructor);
CREATE UNIQUE INDEX INDICE3 ON INSTRUCTORES (idInstructor);
CREATE UNIQUE INDEX INDICE4 ON INSTRUCTORES (idUsuarioFK);

/*VALORES UNICOS PARA LA TABLA CLIENTES*/
CREATE UNIQUE INDEX INDICE5 ON CLIENTES (correoCliente);
CREATE UNIQUE INDEX INDICE7 ON CLIENTES (telefonoCliente);
CREATE UNIQUE INDEX INDICE8 ON CLIENTES (idCliente);
CREATE UNIQUE INDEX INDICE9 ON CLIENTES (idUsuarioFK);

/*VALORES UNICOS PARA LA TABLA USUARIOS*/
CREATE UNIQUE INDEX INDICE10 ON USUARIOS (NumeroIdentificacion);

